# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jhs', '0002_auto_20160418_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsureCompany',
            new_name='Insure_Company',
        ),
    ]
