# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jhs', '0003_auto_20160418_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsureCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('fullname', models.CharField(blank=True, max_length=30)),
                ('url', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InsureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('fullname', models.CharField(blank=True, max_length=30)),
                ('minAge', models.SmallIntegerField()),
                ('maxAge', models.SmallIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jhs.InsureCompany')),
            ],
        ),
        migrations.DeleteModel(
            name='Insure_Company',
        ),
    ]
