# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhs', '0004_auto_20160418_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuretype',
            name='feebase',
            field=models.FloatField(default=10000, max_length=10),
        ),
    ]
