# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhs', '0005_insuretype_feebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsureFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insure_code', models.IntegerField(verbose_name=6)),
                ('sex', models.IntegerField(verbose_name=1)),
                ('bxq', models.CharField(max_length=10)),
                ('lqage', models.CharField(max_length=10)),
                ('jfq', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=10)),
                ('planN', models.CharField(max_length=10)),
                ('other', models.CharField(max_length=10)),
                ('age0', models.FloatField(blank=True, max_length=10)),
            ],
        ),
    ]
