# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhs', '0007_insurefee_age1'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurefee',
            name='age10',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age11',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age12',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age13',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age14',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age15',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age16',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age17',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age18',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age19',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age2',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age20',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age21',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age22',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age23',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age24',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age25',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age26',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age27',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age28',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age29',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age3',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age30',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age31',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age32',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age33',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age34',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age35',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age36',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age37',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age38',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age39',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age4',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age40',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age41',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age42',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age43',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age44',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age45',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age46',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age47',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age48',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age49',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age5',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age50',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age51',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age52',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age53',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age54',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age55',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age56',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age57',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age58',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age59',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age6',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age60',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age61',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age62',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age63',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age64',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age65',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age66',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age67',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age68',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age69',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age7',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age70',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age71',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age72',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age73',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age74',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age75',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age76',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age77',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age78',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age79',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age8',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age80',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='insurefee',
            name='age9',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='insurefee',
            name='age0',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='insurefee',
            name='age1',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
