# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jhs', '0008_auto_20160418_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsureType',
            new_name='Insure',
        ),
    ]
